# Makefile para instalar PHP e Composer dependendo do SO com versões específicas

.PHONY: dependencies php composer cleanup install-local install-production

dependencies: php composer cleanup

# Definindo versões específicas
PHP_VERSION=8.3
COMPOSER_VERSION=2.8
POSTGRES_CLIENT=16
NODE_VERSION=20

php:
    @echo "Instalando PHP $(PHP_VERSION) no Linux..."
    sudo apt-get update
    sudo apt-get install -y software-properties-common apt-transport-https
    sudo add-apt-repository ppa:ondrej/php
    sudo apt-get update
	sudo apt-get update \
		&& sudo apt-get install -y gnupg gosu curl ca-certificates zip unzip git supervisor sqlite3 libcap2-bin libpng-dev python2 dnsutils \
		&& sudo curl -sS 'https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x14aa40ec0831756756d7f66c4f4ea0aae5267a6c' | sudo gpg --dearmor | sudo tee /usr/share/keyrings/ppa_ondrej_php.gpg > sudo /dev/null \
		&& sudo echo "deb [signed-by=/usr/share/keyrings/ppa_ondrej_php.gpg] https://ppa.launchpadcontent.net/ondrej/php/ubuntu jammy main" > sudo /etc/apt/sources.list.d/ppa_ondrej_php.list \
		&& sudo apt-get update \
		&& sudo apt-get install -y php$(PHP_VERSION)-cli php$(PHP_VERSION)-dev \
			php$(PHP_VERSION)-pgsql php$(PHP_VERSION)-sqlite3 php$(PHP_VERSION)-gd \
			php$(PHP_VERSION)-curl \
			php$(PHP_VERSION)-imap php$(PHP_VERSION)-mbstring \
			php$(PHP_VERSION)-xml php$(PHP_VERSION)-zip php$(PHP_VERSION)-bcmath php$(PHP_VERSION)-soap \
			php$(PHP_VERSION)-intl php$(PHP_VERSION)-readline \
			php$(PHP_VERSION)-ldap \
			php$(PHP_VERSION)-msgpack php$(PHP_VERSION)-igbinary php$(PHP_VERSION)-redis \
			php$(PHP_VERSION)-memcached php$(PHP_VERSION)-pcov \
		&& sudo curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | sudo gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg \
		&& echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_$(NODE_VERSION).x nodistro main" | sudo tee /etc/apt/sources.list.d/nodesource.list \
		&& sudo apt-get update \
		&& sudo apt-get install -y nodejs \
		&& sudo npm install -g npm \
		&& sudo curl -sS https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo gpg --dearmor | sudo tee /usr/share/keyrings/pgdg.gpg > sudo /dev/null \
		&& sudo echo "deb [signed-by=/usr/share/keyrings/pgdg.gpg] http://apt.postgresql.org/pub/repos/apt jammy-pgdg main" > sudo /etc/apt/sources.list.d/pgdg.list \
		&& sudo apt-get update \
		&& sudo apt-get install -y postgresql-client-$(POSTGRES_CLIENT)
		&& sudo setcap "cap_net_bind_service=+ep" /usr/bin/php$(PHP_VERSION)

composer:
    @echo "Instalando Composer $(COMPOSER_VERSION) no Linux..."
    curl -sS https://getcomposer.org/installer | php -- --version=$(COMPOSER_VERSION)
    sudo mv composer.phar /usr/local/bin/composer

cleanup:
	sudo apt-get -y autoremove \
		&& sudo apt-get clean \
		&& sudo rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

install-local: dependencies
	sudo apt-get update -y && apt-get install -y php$(PHP_VERSION)-xdebug
	cp .env.example .env
	composer install
	php artisan key:generate
	php artisan optimize:clear
	php artisan octane:install --server=frankenphp

install-production: dependencies
	cp .env.example .env
	composer install --no-dev -o
	php artisan key:generate
	php artisan optimize
	php artisan octane:install --server=frankenphp
