services:
    database:
        image: 'postgres:16.0-alpine3.18'
        ports:
            - '${FORWARD_DB_PORT:-5432}:5432'
        environment:
            PGPASSWORD: '${DB_PASSWORD:-secret}'
            POSTGRES_DB: '${DB_DATABASE}'
            POSTGRES_USER: '${DB_USERNAME}'
            POSTGRES_PASSWORD: '${DB_PASSWORD:-secret}'
        volumes:
            - 'pgsqlvol:/var/lib/postgresql/data'
            - '../database/scripts/create-testing-database.sql:/docker-entrypoint-initdb.d/10-create-testing-database.sql'
        
volumes:
    pgsqlvol:
        driver: local
