name: Push-to-EC2

on:
  push:
    branches:
    - main

permissions:
  id-token: write
  contents: read
  
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
          
      - name: Deploy to AWS EC2
        run: |
          echo "${{ secrets.AWS_INSTANCE_SSH_KEY }}" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${{ secrets.AWS_INSTANCE_SSH_HOST }} '
          cd /home/ubuntu/app && 
          git pull && 
          composer install --no-dev -o && 
          php artisan optimize &&
          sudo supervisorctl restart all
          '
